version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
  - package-ecosystem: gradle
    directory: "/Apps/Android"
    schedule:
      interval: weekly
    commit-message:
      prefix: build
