#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret names set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

banner "Xcode Cloud → TestFlight"

say "This walkthrough uses team 4V4EGQ6LZA and bundle ID com.opencapture.openpocketcine."
say "Signing stays Automatic; Xcode Cloud manages certificates and profiles."
note "Repo hooks already generate the Xcode project and attach What to Test notes."
pause "Ready to start?"

# ── 1. App record ────────────────────────────────────────────────────────
stage "App Store Connect — app record"
say "Reuse the existing OpenPocketCine app (SKU 002) for com.opencapture.openpocketcine."
say "Do not create a second app for the same bundle ID."
open_url "https://appstoreconnect.apple.com/apps"
step "Find the iOS app whose bundle ID is com.opencapture.openpocketcine."
step "If none exists: My Apps → (+) → New App → iOS."
step "Name: OpenPocketCine. Primary language: English. Bundle ID: com.opencapture.openpocketcine."
step "SKU: openpocketcine (or any unique SKU). User Access: Full Access."
pause "App record is open?"

# ── 2. App information ───────────────────────────────────────────────────
stage "App Information — privacy and category"
say "TestFlight needs a privacy policy URL before external testers can install."
open_url "https://appstoreconnect.apple.com/apps"
step "Open the app → App Information."
step "Privacy Policy URL: https://openpocketcine.app/privacy/"
step "Category: Photo & Video (or the closest match)."
note "Support URL for later store listing: https://openpocketcine.app/support/"
pause "Privacy policy URL is saved?"

# ── 3. Connect GitHub ────────────────────────────────────────────────────
stage "Xcode Cloud — grant GitHub access"
say "Xcode Cloud must see erik-sutton95/OpenPocketCine (private is fine)."
open_url "https://appstoreconnect.apple.com/access/integrations"
step "Users and Access → Integrations, or the Xcode Cloud product page."
step "Connect GitHub if it is not already connected (same account as OpenZCine)."
step "Grant access to the OpenPocketCine repository."
note "If a workflow pointed at the pre-squash repo, reconnect it to this one."
pause "GitHub repo is connected to Xcode Cloud?"

# ── 4. Open the local project ────────────────────────────────────────────
stage "Open the generated Xcode project"
say "Xcode Cloud workflows are created from a local project. The xcodeproj is generated."
step "This will run: cd ios && xcodegen generate && open OpenPocketCine.xcodeproj"
if confirm "Generate and open the Xcode project now?"; then
  (cd "$(git rev-parse --show-toplevel)/ios" && xcodegen generate && open OpenPocketCine.xcodeproj)
  say "Xcode should be opening OpenPocketCine.xcodeproj."
else
  note "Run later: cd ios && xcodegen generate && open OpenPocketCine.xcodeproj"
fi
pause "Xcode is showing the OpenPocketCine scheme?"

# ── 5. Create the workflow ───────────────────────────────────────────────
stage "Create the Archive workflow"
say "In Xcode: Report navigator (the speech-bubble / graph icon) → Cloud tab."
say "Or App Store Connect → the app → Xcode Cloud → Manage Workflows → (+)."
step "Start condition: Branch Changes on main."
step "Files and Folders: Sources/, Tests/, ios/, Package.swift, scripts/, justfile."
step "Environment: latest released Xcode and macOS."
step "Actions: Archive — iOS, scheme OpenPocketCine, deployment TestFlight and App Store."
step "Do not pick Internal Testing only if you want an external TestFlight group later."
step "Post-actions: TestFlight → your Internal tester group (yourself) for the first smoke."
note "Optional later: add an External Testing post-action after TestFlight App Review."
pause "Workflow is saved?"

# ── 6. Frame.io env (optional) ───────────────────────────────────────────
stage "Optional — Frame.io environment variables"
say "Omit these to ship with Frame.io login disabled (the default)."
if confirm "Add Frame.io secrets to the Xcode Cloud workflow now?"; then
  step "Workflow → Environment → (+) Environment Variable, mark each Secret."
  step "Add FRAMEIO_CLIENT_ID, FRAMEIO_REDIRECT_URI, FRAMEIO_URL_SCHEME."
  note "Values come from Adobe Developer Console — same as Frameio.local.xcconfig."
  ask FRAMEIO_CLIENT_ID "FRAMEIO_CLIENT_ID (Enter skips):"
  ask FRAMEIO_REDIRECT_URI "FRAMEIO_REDIRECT_URI (Enter skips):"
  ask FRAMEIO_URL_SCHEME "FRAMEIO_URL_SCHEME (Enter skips):"
  [[ -n "${FRAMEIO_CLIENT_ID}" ]] && write_env FRAMEIO_CLIENT_ID "$FRAMEIO_CLIENT_ID"
  [[ -n "${FRAMEIO_REDIRECT_URI}" ]] && write_env FRAMEIO_REDIRECT_URI "$FRAMEIO_REDIRECT_URI"
  [[ -n "${FRAMEIO_URL_SCHEME}" ]] && write_env FRAMEIO_URL_SCHEME "$FRAMEIO_URL_SCHEME"
  note "Paste those into the Xcode Cloud workflow Environment tab if you have not already."
else
  note "Skipping. ci_post_clone.sh will warn and the build will not offer Frame.io login."
fi
pause "Frame.io choice is done?"

# ── 7. First build ───────────────────────────────────────────────────────
stage "Start the first TestFlight build"
say "If this bundle ID already has TestFlight builds from private R&D, set Next Build Number"
say "above that high-water mark in the workflow settings before starting."
step "In Xcode Cloud (or ASC → Xcode Cloud), Start Build on main."
step "Watch ci_post_clone.sh: it must run xcodegen before the archive."
step "When processing finishes, App Store Connect → TestFlight → Internal Testing."
step "Add yourself, install from the TestFlight app, pair a Pocket 4 / 4 Pro."
note "The first external build of 0.1.0 sits in TestFlight App Review. Internal testers do not wait."
note "Tester copy is ios/TestFlight/WhatToTest.en-US.txt."
confirm "Start the first build now (you'll click Start Build in Xcode/ASC)?" || true
pause "Build is running or queued?"
note "Details and troubleshooting: docs/testflight-ci.md"

finish

