#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret names set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
cd "$ROOT"
ENV_FILE="$ROOT/.env"
mkdir -p "$ROOT/.local"

set_play_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" --env play-closed >/dev/null 2>&1; then
      WRITTEN_SECRET+=("play-closed/$name")
      printf '  %s✓ set%s GitHub environment secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub environment secret play-closed/$name")
  warn "skipped $name — later: printf '…' | gh secret set $name --env play-closed"
}

ensure_play_environment() {
  if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
    SKIPPED+=("GitHub Environment play-closed")
    warn "gh is not ready — create Environment play-closed in the repo Settings → Environments"
    return
  fi
  local repo
  repo="$(gh repo view --json nameWithOwner --jq .nameWithOwner)"
  if gh api --method PUT "repos/${repo}/environments/play-closed" >/dev/null; then
    printf '  %s✓ environment%s play-closed\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("GitHub Environment play-closed")
    warn "could not create the play-closed environment"
  fi
}

TOTAL_STAGES=11

banner "Google Play closed testing"

say "This is the Android analog of Xcode Cloud → TestFlight."
say "Package: com.opencapture.openpocketcine. Track: Closed testing (alpha)."
say "Secrets go in the play-closed GitHub Environment, never in pull_request workflows."
note "Privacy policy is already live: https://openpocketcine.app/privacy/"
pause "Ready to start?"

# ── 1. Developer account ─────────────────────────────────────────────────
stage "Play Console — developer account"
say "A one-time \$25 Google Play developer account is required. Skip this stage if you already have one."
open_url "https://play.google.com/console"
step "Sign in with the Google account that should own OpenPocketCine."
step "If Play asks to pay the registration fee, complete it. Identity verification can take hours."
step "If you already see All apps, you are done here."
pause "Play Console is open on your developer account?"

# ── 2. Create the app ────────────────────────────────────────────────────
stage "Create the app record"
say "Create one app. The package name locks to the first AAB you upload."
open_url "https://play.google.com/console/u/0/developers"
step "All apps → Create app."
step "App name: OpenPocketCine. Default language: English (United States)."
step "App or game: App. Free or paid: Free."
step "Accept the declarations Play shows (privacy policy, US export laws, etc.)."
note "Do not create a second app for the same package. Do not set production yet."
pause "The OpenPocketCine app dashboard is open?"

# ── 3. Store listing ─────────────────────────────────────────────────────
stage "Store listing — copy and privacy"
say "Closed testing still needs a listing, privacy policy, and graphics. You can save a draft."
open_url "https://play.google.com/console"
step "Select OpenPocketCine → Grow → Store presence → Store listing (or Main store listing)."
step "App name: OpenPocketCine"
step "Short description (80 characters): Open-source field monitor for DJI Osmo. Live view, scopes, camera control."
step "Full description: paste from docs/android-play-ci.md (Store listing copy)."
step "App category: Photography (or Video Players & Editors if Photography is gone)."
step "Email: a mailbox you read. Privacy policy: https://openpocketcine.app/privacy/"
step "Phone screenshots: Android captures of the monitor, not iPhone screenshots. At least 2."
step "Hi-res icon: 512×512 PNG. Feature graphic: 1024×500. Use site/assets/icon.png as a start."
note "Support URL: https://openpocketcine.app/support/"
pause "Listing fields are saved, even if graphics are still TODO?"

# ── 4. Questionnaires ────────────────────────────────────────────────────
stage "Rating, audience, and Data safety"
say "Play will not review a closed-testing release until these are complete."
open_url "https://play.google.com/console"
step "Policy → App content → Complete all required tasks."
step "Content rating: fill the IARC questionnaire (Photo/Video; no user-generated public content)."
step "Target audience: 18+ is honest for a production tool. Not a news app."
step "News app: No. COVID-19: No. Data safety: the app has no account and no analytics."
step "Data safety details: Wi-Fi passwords stay in Keystore on the phone; optional website waitlist is not in the app."
step "Advertising ID: No. Government app: No."
note "If a task is still red, finish it before the first closed-testing review."
pause "App content tasks are all green, or you know which ones remain?"

# ── 5. Closed testing track ──────────────────────────────────────────────
stage "Closed testing track"
say "Internal testing is capped at 100 testers. The waitlist is 300+, so this is Closed testing."
open_url "https://play.google.com/console"
step "Test and release → Testing → Closed testing."
step "Use the default closed track (often named Closed testing / alpha). Create one if Play asks."
step "Countries: start with the countries your testers actually live in."
step "Testers → Create email list → name it waitlist. You will upload .local/play-testers.csv later."
step "Copy the opt-in URL. It looks like https://play.google.com/apps/testing/com.opencapture.openpocketcine"
note "The URL 404s until the first AAB is up and the track is active. Copy it anyway once Play shows it."
ask PLAY_JOIN_URL "Paste the join URL (Enter keeps the default):"
if [[ -z "${PLAY_JOIN_URL}" ]]; then
  PLAY_JOIN_URL="https://play.google.com/apps/testing/com.opencapture.openpocketcine"
fi
write_env PLAY_JOIN_URL "$PLAY_JOIN_URL"
pause "Closed track exists and the join URL is saved?"

# ── 6. Upload keystore ───────────────────────────────────────────────────
stage "Upload keystore"
say "Play App Signing holds the app key. We keep an upload key in .local/ (gitignored)."
KEYSTORE="$ROOT/.local/play-upload.keystore"
if [[ -f "$KEYSTORE" ]]; then
  note "Reusing existing $KEYSTORE"
  ask_secret ANDROID_KEYSTORE_PASSWORD "Password for that keystore:"
  ask ANDROID_KEY_ALIAS "Key alias [upload]:"
  ANDROID_KEY_ALIAS="${ANDROID_KEY_ALIAS:-upload}"
  ask_secret ANDROID_KEY_PASSWORD "Key password (Enter = same as store):"
  ANDROID_KEY_PASSWORD="${ANDROID_KEY_PASSWORD:-$ANDROID_KEYSTORE_PASSWORD}"
else
  say "This generates a 2048-bit RSA upload key, valid ~27 years."
  ask_secret ANDROID_KEYSTORE_PASSWORD "Choose a keystore password:"
  if [[ -z "${ANDROID_KEYSTORE_PASSWORD}" ]]; then
    warn "password was empty — skip keytool and set this later"
  else
    ANDROID_KEY_ALIAS="upload"
    ANDROID_KEY_PASSWORD="$ANDROID_KEYSTORE_PASSWORD"
    keytool -genkeypair -v \
      -keystore "$KEYSTORE" \
      -alias "$ANDROID_KEY_ALIAS" \
      -keyalg RSA -keysize 2048 -validity 10000 \
      -storepass "$ANDROID_KEYSTORE_PASSWORD" \
      -keypass "$ANDROID_KEY_PASSWORD" \
      -dname "CN=OpenPocketCine, OU=Play Upload, O=OpenPocketCine, C=US"
    chmod 600 "$KEYSTORE"
    say "wrote $KEYSTORE"
  fi
fi
if [[ -f "$KEYSTORE" && -n "${ANDROID_KEYSTORE_PASSWORD:-}" ]]; then
  write_env ANDROID_KEYSTORE_FILE "$KEYSTORE"
  write_env ANDROID_KEYSTORE_PASSWORD "$ANDROID_KEYSTORE_PASSWORD"
  write_env ANDROID_KEY_ALIAS "${ANDROID_KEY_ALIAS:-upload}"
  write_env ANDROID_KEY_PASSWORD "${ANDROID_KEY_PASSWORD:-$ANDROID_KEYSTORE_PASSWORD}"
  ANDROID_KEYSTORE_BASE64="$(base64 < "$KEYSTORE" | tr -d '\n')"
fi
note "Never commit .local/play-upload.keystore. Hygiene already blocks *.keystore."
pause "Upload keystore is on disk?"

# ── 7. Google Cloud API ──────────────────────────────────────────────────
stage "Google Play Developer API"
say "CI talks to Play through a service account, not your personal Google login."
open_url "https://console.cloud.google.com/apis/library/androidpublisher.googleapis.com"
step "Select or create a Google Cloud project (name it openpocketcine-play is fine)."
step "Enable the Google Play Android Developer API."
note "Play Console no longer has a dedicated API access page on many accounts — Users and permissions is the grant."
pause "The Android Publisher API is enabled?"

# ── 8. Service account ───────────────────────────────────────────────────
stage "Service account + Play permissions"
say "Create a JSON key, then invite that robot email into Play Console."
open_url "https://console.cloud.google.com/iam-admin/serviceaccounts"
step "Create service account. Name: play-upload. ID: play-upload."
step "Skip Cloud IAM roles — Play Console owns the permissions."
step "Open the account → Keys → Add key → Create new key → JSON. The file downloads."
step "Copy the service account email (it ends with .iam.gserviceaccount.com)."
open_url "https://play.google.com/console/users-and-permissions"
step "Users and permissions → Invite new users."
step "Paste the service account email."
step "App permissions (OpenPocketCine only): View app information; Release apps to testing tracks; Manage testing tracks and edit tester lists."
step "Do not grant production, financial, or Admin unless you want that later."
step "Invite user. Propagation can take a few minutes (rarely up to an hour)."
ask PLAY_SA_JSON_PATH "Path to the downloaded JSON key:"
PLAY_SA_JSON_PATH="${PLAY_SA_JSON_PATH/#\~/$HOME}"
if [[ -n "${PLAY_SA_JSON_PATH}" && -f "${PLAY_SA_JSON_PATH}" ]]; then
  cp "$PLAY_SA_JSON_PATH" "$ROOT/.local/play-service-account.json"
  chmod 600 "$ROOT/.local/play-service-account.json"
  write_env PLAY_SERVICE_ACCOUNT_JSON_FILE "$ROOT/.local/play-service-account.json"
  say "copied to .local/play-service-account.json"
else
  warn "JSON path missing — you can still set the GitHub secret by hand later"
fi
pause "Service account is invited in Play Console?"

# ── 9. GitHub Environment ────────────────────────────────────────────────
stage "GitHub Environment play-closed"
say "The upload workflow reads secrets only from this environment. Pull requests never see them."
ensure_play_environment
if [[ -n "${ANDROID_KEYSTORE_BASE64:-}" ]]; then
  set_play_secret ANDROID_KEYSTORE_BASE64 "$ANDROID_KEYSTORE_BASE64"
  set_play_secret ANDROID_KEYSTORE_PASSWORD "$ANDROID_KEYSTORE_PASSWORD"
  set_play_secret ANDROID_KEY_ALIAS "${ANDROID_KEY_ALIAS:-upload}"
  set_play_secret ANDROID_KEY_PASSWORD "${ANDROID_KEY_PASSWORD:-$ANDROID_KEYSTORE_PASSWORD}"
fi
if [[ -f "$ROOT/.local/play-service-account.json" ]] && command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if gh secret set PLAY_SERVICE_ACCOUNT_JSON --env play-closed < "$ROOT/.local/play-service-account.json"; then
    WRITTEN_SECRET+=("play-closed/PLAY_SERVICE_ACCOUNT_JSON")
    printf '  %s✓ set%s GitHub environment secret PLAY_SERVICE_ACCOUNT_JSON\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("GitHub environment secret play-closed/PLAY_SERVICE_ACCOUNT_JSON")
  fi
fi
note "Do not add these secrets to the CI pull_request workflow."
pause "Environment secrets are set, or listed as still-to-do?"

# ── 10. First AAB ────────────────────────────────────────────────────────
stage "First App Bundle"
say "The Play Developer API needs the package to exist. The first AAB is a console upload."
note "just android-bundle signs with the keystore from .env and writes app-release.aab"
if confirm "Build a signed bundle on this machine now?"; then
  if just android-bundle; then
    say "AAB: Apps/Android/app/build/outputs/bundle/release/app-release.aab"
  else
    warn "bundle failed — you can run just android-bundle after the Swift Android SDK is installed"
    SKIPPED+=("local bundleRelease")
  fi
else
  note "Run later: just android-bundle"
fi
open_url "https://play.google.com/console"
step "Test and release → Closed testing → Create new release."
step "Upload the AAB. Play App Signing enrolls on this first bundle — keep the upload keystore."
step "Release name can stay the version Play fills. What's new: Apps/Android/Play/whatsnew/whatsnew-en-US"
step "Save. Send for review if the listing tasks are green; otherwise keep it draft."
note "After this first upload, GitHub Actions can ship the rest."
pause "First AAB is uploaded (draft or in review)?"

# ── 11. Testers + auto-upload ────────────────────────────────────────────
stage "Testers and auto-upload"
say "Do not enable auto-upload until the first closed release is accepted."
step "Export the Tally waitlist CSV. Keep it out of git."
step "python3 scripts/prepare-android-testers.py ~/Downloads/tally.csv"
step "Play Console → Closed testing → Testers → upload .local/play-testers.csv"
step "Copy the join URL into .env if it changed (PLAY_JOIN_URL)."
if confirm "Turn on ANDROID_PLAY_UPLOAD so merges to main ship to closed testing?"; then
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    gh variable set ANDROID_PLAY_UPLOAD --body true
    say "Auto-upload is on. Path-filtered pushes to main will bundle and upload."
  else
    SKIPPED+=("GitHub variable ANDROID_PLAY_UPLOAD")
    warn "Set it later: gh variable set ANDROID_PLAY_UPLOAD --body true"
  fi
else
  note "Leave it off. Dispatch Android Play from the Actions tab until you are ready."
fi
note "Details: docs/android-play-ci.md"

finish

