#!/usr/bin/env python3
"""Write gitignored Reliability.local.xcconfig from SENTRY_DSN_IOS or SENTRY_DSN.

xcconfig treats // as a comment, so a literal https:// DSN would truncate.
This writes https:/$()/host… and never prints the DSN.
"""

from __future__ import annotations

import argparse
import os
import sys
from urllib.parse import urlparse

EXIT_OK = 0
EXIT_CONFIG = 2


def env_value(*names: str) -> str:
    for name in names:
        value = os.environ.get(name, "").strip()
        if value:
            return value
    return ""


def validated_dsn(raw: str) -> str | None:
    trimmed = raw.strip()
    if not trimmed or "YOUR_" in trimmed or "example" in trimmed.lower():
        return None
    # Accept an already-encoded xcconfig value by restoring the scheme slashes.
    candidate = trimmed.replace("https:/$()/", "https://", 1)
    url = urlparse(candidate)
    if url.scheme.lower() != "https":
        return None
    if not url.hostname or not url.username:
        return None
    if url.password or url.query or url.fragment:
        return None
    parts = [p for p in url.path.split("/") if p]
    if not parts or not parts[-1].isdigit():
        return None
    return candidate


def xcconfig_assignment(dsn: str) -> str:
    if not dsn:
        return "SENTRY_DSN =\n"
    if dsn.startswith("https://"):
        return "SENTRY_DSN = https:/$()/" + dsn[len("https://") :] + "\n"
    raise ValueError("internal: DSN must be https after validation")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", required=True, help="Path to Reliability.local.xcconfig")
    parser.add_argument(
        "--require",
        action="store_true",
        help="Fail when the DSN is missing or invalid (enabled deployments)",
    )
    args = parser.parse_args(argv)

    raw = env_value("SENTRY_DSN_IOS", "SENTRY_DSN")
    dsn = validated_dsn(raw) if raw else None
    if args.require and not dsn:
        print(
            "sentry-dsn-xcconfig: enabled deployment needs SENTRY_DSN_IOS or SENTRY_DSN "
            "(https public DSN with a numeric project path)",
            file=sys.stderr,
        )
        return EXIT_CONFIG
    if raw and not dsn:
        print("sentry-dsn-xcconfig: DSN is not a valid https Sentry DSN", file=sys.stderr)
        return EXIT_CONFIG

    out_path = args.out
    parent = os.path.dirname(os.path.abspath(out_path))
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("// Generated by tools/sentry-dsn-xcconfig.py. Do not commit.\n")
        handle.write(xcconfig_assignment(dsn or ""))
    if dsn:
        print("sentry-dsn-xcconfig: wrote xcconfig-safe SENTRY_DSN")
    else:
        print("sentry-dsn-xcconfig: wrote empty SENTRY_DSN")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
